server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: my-postgres-app
    
  web:
    resources:
      static-locations: classpath:/static/

  datasource:
    url: jdbc:postgresql://localhost:5432/Test
    username: Alfred
    password: alfybooze
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    static-location: classpath:/static/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true  # Set to true in production for better performance
 